# Generated by Django 6.0.5 on 2026-05-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_userpreference_manual_baseline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inflationsource",
            name="code",
            field=models.CharField(
                choices=[
                    ("ECB_AT", "Austria (ECB)"),
                    ("ECB_BE", "Belgium (ECB)"),
                    ("ECB_BG", "Bulgaria (ECB)"),
                    ("ECB_HR", "Croatia (ECB)"),
                    ("ECB_CY", "Cyprus (ECB)"),
                    ("ECB_CZ", "Czechia (ECB)"),
                    ("ECB_DK", "Denmark (ECB)"),
                    ("ECB_EE", "Estonia (ECB)"),
                    ("ECB_FI", "Finland (ECB)"),
                    ("ECB_FR", "France (ECB)"),
                    ("ECB_DE", "Germany (ECB)"),
                    ("ECB_GR", "Greece (ECB)"),
                    ("ECB_HU", "Hungary (ECB)"),
                    ("ECB_IE", "Ireland (ECB)"),
                    ("ECB_IT", "Italy (ECB)"),
                    ("ECB_LV", "Latvia (ECB)"),
                    ("ECB_LT", "Lithuania (ECB)"),
                    ("ECB_LU", "Luxembourg (ECB)"),
                    ("ECB_MT", "Malta (ECB)"),
                    ("ECB_NL", "Netherlands (ECB)"),
                    ("ECB_PL", "Poland (ECB)"),
                    ("ECB_PT", "Portugal (ECB)"),
                    ("ECB_RO", "Romania (ECB)"),
                    ("ECB_SK", "Slovakia (ECB)"),
                    ("ECB_SI", "Slovenia (ECB)"),
                    ("ECB_ES", "Spain (ECB)"),
                    ("ECB_SE", "Sweden (ECB)"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
